name: pi_thing
description: "An unofficial Raspberry Pi companion app for Spotify inspired by the Car Thing"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  clock: ^1.1.1
  dio: ^5.7.0
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.4.1
  json_annotation: ^4.9.0
  palette_generator: ^0.3.3+5
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.2
  text_scroll: ^0.2.0
  url_launcher: ^6.3.1
  win32: ^5.8.0

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
