name: pi_thing
description: "An unofficial Raspberry Pi companion app for Spotify inspired by the Car Thing"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
